kind = "mobile"
previewPath = "/clientverse-mobile/"
title = "ClientVerse Mobile"
version = "1.0.0"
id = "artifacts/clientverse-mobile"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
paths = [ "/clientverse-mobile/" ]
localPort = 5000

[services.development]
run = "pnpm --filter @workspace/clientverse-mobile run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/clientverse-mobile", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/clientverse-mobile", "run", "serve" ]

[services.env]
PORT = "5000"
BASE_PATH = "/clientverse-mobile/"
